firstgrade = input (" Enter first grade out of 100 : ")
secondgrade = input (" Enter second grade out of 100 : ")
thirdgrade = input (" Enter third grade out of 100 : ")
x = float (firstgrade)
y = float (secondgrade)
z = float (thirdgrade)
final_grade = ((30*x)/100)+((30*y)/100)+((40*z)/100)
print ("The final grade is equal to ", final_grade)
